analyzer:
  # plugins:
  #   - dart_code_metrics
  exclude:
    # Web
    - "web/**"
    # Build
    - "build/**"
    # Generated code
    - "lib/**.g.dart"
    - "lib/**.freezed.dart"
    - "lib/**.graphql.dart"
    - "lib/generated_plugin_registrant.dart"
    - ".test_coverage.dart"
    - "lib/pigeon.dart"
    - "lib/generated/**"
    # Assets
    - "assets/**"
    # Mocks for test
    - "test/data/**"

linter:
  rules:
    #Flutter
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    package_names: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true

    #Effective Dart
    # STYLE
    camel_case_types: true
    camel_case_extensions: true
    library_names: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    constant_identifier_names: true # prefer
    directives_ordering: true
    # lines_longer_than_80_chars: false # avoid
    curly_braces_in_flow_control_structures: true

    # DOCUMENTATION
    slash_for_doc_comments: true
    package_api_docs: true # prefer
    # public_member_api_docs: false # prefer
    #comment_references # Unused because https://github.com/dart-lang/sdk/issues/36974

    # USAGE
    implementation_imports: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true # prefer
    unnecessary_brace_in_string_interps: true # avoid
    prefer_collection_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_function_literals_in_foreach_calls: true # avoid
    prefer_iterable_whereType: true
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true
    prefer_equal_for_default_values: true
    avoid_init_to_null: true
    unnecessary_getters_setters: true
    # prefer_expression_function_bodies: true # consider
    unnecessary_this: true
    prefer_initializing_formals: true
    type_init_formals: true
    empty_constructor_bodies: true
    unnecessary_new: true
    unnecessary_const: true
    avoid_catches_without_on_clauses: true # avoid
    avoid_catching_errors: true
    use_rethrow_when_possible: true

    # DESIGN
    use_to_and_as_if_applicable: true # prefer
    one_member_abstracts: true # avoid
    avoid_classes_with_only_static_members: true # avoid
    # prefer_mixin: true
    prefer_final_fields: true # prefer
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    avoid_returning_null: true # avoid
    avoid_returning_this: true # avoid
    type_annotate_public_apis: true # prefer
    prefer_typing_uninitialized_variables: true # consider
    omit_local_variable_types: true # avoid
    avoid_types_on_closure_parameters: true # avoid
    avoid_return_types_on_setters: true
    prefer_generic_function_type_aliases: true
    avoid_private_typedef_functions: true # prefer
    use_function_type_syntax_for_parameters: true # consider
    avoid_positional_boolean_parameters: true # avoid
    hash_and_equals: true
    avoid_equals_and_hash_code_on_mutable_classes: false # avoid
    avoid_null_checks_in_equality_operators: true

    # Pedantic
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    empty_catches: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    recursive_getters: true
    sort_child_properties_last: true
    unawaited_futures: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
    valid_regexps: true

    # always_use_package_imports: true
    # avoid_print: true
    # avoid_slow_async_io: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    # invariant_booleans: true
    prefer_const_constructors: true
    # prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    # prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    # prefer_expression_function_bodies: true

    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_is_not_operator: true
    unnecessary_overrides: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_string_buffers: true
